version: '3.7'

services:
  vue:
    container_name: vue-rithual
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'